# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - Carthage
enabled_rules:
  - empty_count
  - force_unwrapping
disabled_rules:
 - cyclomatic_complexity
 - line_length
 - opening_brace
 - todo
