# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - Carthage
opt_in_rules:
  - conditional_returns_on_newline
  - empty_count
  # - force_unwrapping
  - missing_docs
  - private_outlet
  - vertical_whitespace
disabled_rules:
  - closure_parameter_position
  - cyclomatic_complexity
  - implicit_getter
  - line_length
  - todo
  - trailing_comma
  - unused_closure_parameter
  - void_return
  - weak_delegate
