language: objective-c

xcode_workspace: Authenticator.xcworkspace
xcode_scheme: Authenticator

osx_image: xcode611
xcode_sdk:
  - iphonesimulator8.1

before_install:
  - export LANG=en_US.UTF-8
  - gem update cocoapods --no-document
  - brew update
  - brew upgrade xctool
