language: objective-c

xcode_workspace: Authenticator.xcworkspace
xcode_scheme: Authenticator
xcode_sdk:
  - iphonesimulator8.0

before_install:
  - export LANG=en_US.UTF-8
  - gem update cocoapods --no-document
  - brew update
  - brew upgrade xctool
