language: objective-c
xcode_workspace: Authenticator.xcworkspace
xcode_scheme: Authenticator
xcode_sdk: iphonesimulator

before_install:
  - export LANG=en_US.UTF-8
  - gem update cocoapods
  - brew update
  - brew upgrade xctool
