language: objective-c
xcode_workspace: Authenticator.xcworkspace
xcode_scheme: Authenticator
xcode_sdk: iphonesimulator

before_script:
  - export LANG=en_US.UTF-8

before_install:
  gem update cocoapods
