language: objective-c

xcode_workspace: Authenticator.xcworkspace
xcode_scheme: Authenticator
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1

before_install:
  - export LANG=en_US.UTF-8
  - gem update cocoapods
  - brew update
  - brew upgrade xctool
