# Configuration for Travis (https://travis-ci.org)

language: objective-c

xcode_workspace: Authenticator.xcworkspace
xcode_scheme: Authenticator

osx_image: xcode8.2
env: DESTINATION="name=iPhone 6s"

matrix:
  include:
    - osx_image: xcode7.3

before_install:
  - git submodule update --init --recursive

script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -destination "$DESTINATION" build test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
