# Configuration for Travis (https://travis-ci.org)

language: objective-c

xcode_workspace: Authenticator.xcworkspace
xcode_scheme: Authenticator

osx_image: xcode8
xcode_sdk: iphonesimulator10.0
env: DESTINATION="platform=iOS Simulator"

matrix:
  include:
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3

before_install:
  - git submodule update --init --recursive

script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -destination "$DESTINATION" build test | xcpretty -c
